plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'

}

group = 'com.github'
version = '0.0.1-SNAPSHOT'
def mapStructVersion = "1.6.3"
def querydslVersion = "7.0"
def generatedDir = "src/main/generated"
def buildDir = "building" //여기는 내가 그냥 jar파일 생성되는 폴더로 사용할생각이다.


java {
    sourceCompatibility = '17'
}
configurations {
//    compileOnly {
//        extendsFrom annotationProcessor
//    }
// QueryDSL과 관련된 라이브러리들이 컴파일 시점에만 필요하도록 설정합니다. 또한, QueryDSL 설정을 컴파일 클래스패스에 추가합니다.
    querydsl.extendsFrom compileClasspath
}

repositories {
    mavenCentral()
}
dependencyManagement {
    imports {
        mavenBom "com.azure.spring:spring-cloud-azure-dependencies:5.19.0"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    //lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    //Mapstruct
    implementation "org.mapstruct:mapstruct:${mapStructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapStructVersion}"
    //Swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    //env-hide
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    //mariadb
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.1.4'
    //jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
    //security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    //redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    //jasypt
    implementation 'com.github.ulisesbocchio:jasypt-spring-boot-starter:3.0.5'
    //email_verification
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    //QueryDsl
    implementation "io.github.openfeign.querydsl:querydsl-jpa:${querydslVersion}"
    annotationProcessor "io.github.openfeign.querydsl:querydsl-apt:${querydslVersion}:jpa"

    //azure storage
    implementation 'com.azure.spring:spring-cloud-azure-starter-storage-blob'

}

tasks.named('test') {
    useJUnitPlatform()
}
//querydsl QClass 파일 생성 위치를 지정 mapperImpl 도 여기서 같이 정해진다.
tasks.withType(JavaCompile).configureEach {
    options.getGeneratedSourceOutputDirectory().set(file(generatedDir))
}
// 소스 코드로 인식할 디렉토리에 경로에 Q-Class 파일을 추가
// 이렇게 하면 Q-Class가 일반 Java 클래스처럼 취급되어 컴파일과 실행 시 클래스패스에 포함됨
// java source set 에 querydsl QClass 위치 추가
sourceSets {
    main.java.srcDirs += [generatedDir]
}


tasks.named('bootJar'){
    mainClass = 'com.github.accountmanagementproject.AccountManagementProjectApplication'
    destinationDirectory = file(buildDir)
    archivesBaseName = '프로젝트이름'
    archiveFileName = 'AccountManagementProject.jar'
    archiveVersion = "3.9.3"
}

clean {
    delete file(buildDir), file(generatedDir)
}