jwtpassword:
  source: ENC(foTHOXMs3+XPmFWjU982ZSZl/HmV971ViWri+mqf/+s/EQ8cCb/0uNoIMOnIv52H/BI8X4+EIQojuAeuXCXB/7gzCKMj8Z6dOpR9asKKEOY=)

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

oauth:
  kakao:
    client-id: ENC(dGY5idd3p5BT7SmM3jAzcOUtcHM6HNAEuE6unhGyusOBtwmbWGRD/j2GHjuNr+AK)
    secret: ENC(tkjxfDY5EHsJlm4hRHqoyCRpnAMsSfUzFgEkC55ssu6VsSrkZts94USxxeYFlnlI)
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-uri: http://localhost:8080/api/auth/kakao
  naver:
    client-id: ENC(ViBdn4cYnxMFSXi0rSs7mnrQBwlfRHzxJnXVbTw7YSE=)
    secret: ENC(YEL+R3qWDgfscQvMgwa1yJN6x/NGOZeq)
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com


spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher #와일드카드사용해서 매칭전략 스웨거도 필요함
  jpa:
    open-in-view: false #지연로딩 성능이슈로인해 false 기본값이 true 임
  datasource:
    username: ENC(Ks/AJ8bjJITh7tfRcSMaZg==)
    password: ENC(nki6d8ZoRQSeteS7d0bbOTdrtX/uvFDg)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(34ItjdybRX8sNKlv04yxywZMul7oyuTDkUONZkuzeHLcriLZot+1JzozA0aB8iF5)
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(tZCNtUD39C1X4xxr3+oP0HZ0q95nukRsjUP0oqK3jOw=)
    password: ENC(yymAj4wB0P5Hy3w4p5kBeV7dImkHJWaYqBtHPX2C3EI=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#              Identity Manager 서버가 SSL을 사용하여 SMTP와 통신하도록 지시합니다.



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /amp-docs.html
  version: 1.0.0

