jwtpassword:
  source: 03E59ECBFF209332DB0EF4003E10813F595CF3DCBFD8FF4E90220546400A22C2


oauth:
  kakao:
    client-id: d7453d5d4fe1c096ca03c1ed009a03ff
    secret: K5U5BQQ9UdpwJvlPC0lP8mWBGQxXTe85
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-uri: http://localhost:8080/api/auth/kakao

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher #와일드카드사용해서 매칭전략 스웨거도 필요함
  jpa:
    open-in-view: false #지연로딩 성능이슈로인해 false 기본값이 true 임
  datasource:
    username: root
    password: aftertime
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/account