spring:
  jpa:
    show-sql: true
  server-url:
    base: ENC(WMGDs3gvS53Dzb0fQ2jTkMyUePXQGwYCnGoI12JgkAk=)
  datasource:
    username: ENC(GVbs+MiVH/NjLAeYsmfmkA==)
    password: ENC(t/FyDozQWnSPjnOPHcGU2WhhhAbjFFO8)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(XGqG4WoIpWIOoPuDRSPBsoan9Re0s1M3xIQxo0k0O3Jb1aLKqPR6G+diG72hvacfBlRt5b7s134=)
