jwt-password:
  source: ENC(foTHOXMs3+XPmFWjU982ZSZl/HmV971ViWri+mqf/+s/EQ8cCb/0uNoIMOnIv52H/BI8X4+EIQojuAeuXCXB/7gzCKMj8Z6dOpR9asKKEOY=)

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

server: # nginx 환경을 위한 설정 포워딩 되기전 정보들을 받아옴
  forward-headers-strategy: native


cool-sms:
  api-key: ENC(MW3p+7iONpDmGUdGQWV1kqibSNSc9Dy0jvXnloXoxpo=)
  api-secret: ENC(ZZ2VFe+nZJKwIRr0u302+4YMZAQvCiY49d8O78C/+lJ0WJFFRrNC9qC1U4UqdPfR)
  domain : https://api.solapi.com
  phone-number: ENC(U3RR4xvGnLE7hSQfVw4aHA13JJjrEduR)

oauth:
  microsoft:
    client-id: ENC(rjiKRyqXBeKynTgatKnOn/mBdAbdYswntEs0uWueeEomcTUV8jjjqhRqh4X3SEYA)
    secret: ENC(xTAFfwdopNu+2NgSOFiriOyYvjIO7ILkMXbbEuxjtsxjecGOqlBKE8P5qYxPbk46PE6PKyAdztI=)
    url:
      auth: https://login.microsoftonline.com
      api: https://graph.microsoft.com
  twitter:
    client-id: ENC(vPOdhl1ySRUQoELKRLLUlGqWKZmd3l9CIR5lv1EXZrkjBbX/0CiWjEZCDzsYxmEa)
    secret: ENC(RwcySflxwrM1umCt+l3rNgAp9ExuHcfLgr6/xEyyp6KRqM75TpLEhxBRwG+pqnKbZwAbzmpB/f0ojtM+iApkrA==)
    url:
      code: https://x.com
      api: https://api.x.com
  facebook:
    client-id: ENC(GZh9OTPMvU+NlvDg64hR3XHqj08cCPUEoZ32eaOP3Lw=)
    secret: ENC(VXz37rV6dg31uXj6tVfZjRn7YWD68DDAM2vZ7SB5X6thJnKZE99ECBabstuTZdCC)
    url:
      code: https://www.facebook.com
      api: https://graph.facebook.com
  kakao:
    client-id: ENC(dGY5idd3p5BT7SmM3jAzcOUtcHM6HNAEuE6unhGyusOBtwmbWGRD/j2GHjuNr+AK)
    secret: ENC(tkjxfDY5EHsJlm4hRHqoyCRpnAMsSfUzFgEkC55ssu6VsSrkZts94USxxeYFlnlI)
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    client-id: ENC(ViBdn4cYnxMFSXi0rSs7mnrQBwlfRHzxJnXVbTw7YSE=)
    secret: ENC(YEL+R3qWDgfscQvMgwa1yJN6x/NGOZeq)
    state: ENC(5cNSEo96ZrDeGqfLU66WKNy/PfH/2+sD/w/LWGa9OuY=)
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
  google:
    client-id: ENC(mzDZ4QLHZGLE7tSHF+igoC6/R75cvYzak/LV5Vunh4B4m2vO7suGI244yBiNnNsaLJjVVh1ta+6m8IrSDczrPpFHOVdVBV3xoynq2XQolYEFmcXDOp97Tg==)
    secret: ENC(6Eg+GrGrf5DLIOcLZVQfB3s8+mbEH+GOECrTjSBJqYH5cdQzr3kMJLf1oCnLfuFn)
    url:
      code: https://accounts.google.com
      auth: https://oauth2.googleapis.com
      api: https://www.googleapis.com
  github:
    client-id: ENC(TluAC7FBfDgVndgxZ7x8gB25K1QoMmYODppYplYHNVw=)
    secret: ENC(2RlxgY5Hwf+y1U0fkRGq+I56tcY5B/PYC47tNvTaVdnzFfCg2AoGvCKfSS2QWNWQN0cnscn1zwc=)
    url:
      auth: https://github.com
      api: https://api.github.com

spring:
  server-url:
    base: ENC(rfDPUVWHEmyfF7eyRscC4D9oHmIplV102ozloablxig=)
    https: ENC(UgOQzgA9vlSBT4BkHQ4ju00cP/JOzt7fNdVhLqAkc+c=)
  mvc:
    path match:
      matching-strategy: ant_path_matcher #와일드카드사용해서 매칭전략 스웨거도 필요함
  jpa:
    open-in-view: false #지연로딩 성능이슈로인해 false 기본값이 true 임
  datasource:
    username: ENC(Ks/AJ8bjJITh7tfRcSMaZg==)
    password: ENC(nki6d8ZoRQSeteS7d0bbOTdrtX/uvFDg)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(34ItjdybRX8sNKlv04yxywZMul7oyuTDkUONZkuzeHLcriLZot+1JzozA0aB8iF5)
    hikari:
      max-lifetime: 177000 # 177초 RDS wait_timeout 180초 보다 짧게 설정
  data:
    redis:
      host: ENC(2KttGDhIqstDjAAlx8vBaqFuBHJdodRA)
      port: 6379
      password: ENC(fuN37Be6K3qdIEggPy++iwek4+8xRtaT)
      timeout: 3000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(tZCNtUD39C1X4xxr3+oP0HZ0q95nukRsjUP0oqK3jOw=)
    password: ENC(yymAj4wB0P5Hy3w4p5kBeV7dImkHJWaYqBtHPX2C3EI=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#              Identity Manager 서버가 SSL을 사용하여 SMTP와 통신하도록 지시합니다.
  #Azure Storage
  cloud:
    azure:
      storage:
        blob:
          account-name: ENC(ghJS3NTt63EZYlsKyrG5M0Ev/wEBJVCTBhkbV2zqX8g=)
          endpoint: ENC(/U5pUyzsYaSXLjk5az1BoOAkyhZ5gFoO8YBj16X39LDVtSQTVL6iu0vbY6QlL+qi1SJn2QNNitqJOhbwaALAfw==)
          container-name: ENC(OJDq6SjjcuPgPZyh4roq6Jepm/aVix15TWOZo4rBUjj45bI//srFew==)
          account-key: ENC(x2zXPfjLV25ErhcJ1PZ+45XvQrPtyCC3E5WoPftyWsvYKWom//84nNHqEzvdoiMFEgkdWhkrpOu3EVkbfq4PyEMqEKaNvzK/4wA8Ug75j+BTJIwvpDQlNPQBZgvVk+oIp4/NeX+M8Ro=)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /amp-docs.html
  version: 1.0.0

