spring:
  jpa:
    show-sql: true
  server-url:
    base: ENC(WMGDs3gvS53Dzb0fQ2jTkMyUePXQGwYCnGoI12JgkAk=)
  datasource:
    username: ENC(GVbs+MiVH/NjLAeYsmfmkA==)
    password: ENC(t/FyDozQWnSPjnOPHcGU2WhhhAbjFFO8)
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(/voEFLuRqvl8UkOvlrWb9kivWvEkB5nDwcCJPFPVtivKJoORcAFL0s8oV3d34le1SdsRqzbZOjqzaqd/anVP3A==)
